# ML Zoomcamp 2026 — Homework 1
## Module 1: Introduction to Machine Learning

**Author:** Rishi P. Kulkarni

This notebook solves Homework 1 using the pinned 2026 Car Fuel Efficiency dataset.

Cell 1 — Imports and environment

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Python environment ready")
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Python environment ready
Pandas version: 2.2.3
NumPy version: 2.1.3


Cell 2 — Download and load the dataset

In [2]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (10000, 11)


,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


Cell 3 — Inspect the dataset

In [3]:
print("Columns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

Columns:
['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors', 'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight', 'acceleration', 'fuel_efficiency_mpg']

Data types:
model_year               int64
origin                  object
fuel_type               object
drivetrain              object
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

Missing values:
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64


Cell 4 — Q1: Pandas version

In [4]:
print("Q1 — Pandas version")
print(pd.__version__)

Q1 — Pandas version
2.2.3


Cell 5 — Q2: Number of records

In [5]:
record_count = len(df)

print("Q2 — Number of records:", record_count)

Q2 — Number of records: 10000


Cell 6 — Q3: Number of fuel types

In [6]:
fuel_types = df["fuel_type"].nunique()

print("Q3 — Number of fuel types:", fuel_types)
print("\nFuel types:")
print(df["fuel_type"].unique())

Q3 — Number of fuel types: 3

Fuel types:
['Gasoline' 'Diesel' 'Hybrid']


Cell 7 — Q4: Columns with missing values

In [7]:
missing_by_column = df.isnull().sum()

columns_with_missing = (missing_by_column > 0).sum()

print("Q4 — Number of columns with missing values:", columns_with_missing)

print("\nMissing values by column:")
print(missing_by_column[missing_by_column > 0])

Q4 — Number of columns with missing values: 2

Missing values by column:
horsepower      877
acceleration    264
dtype: int64


Cell 8 — Q5: Maximum fuel efficiency for Asia

In [9]:
asia = df[df["origin"] == "Asia"]

max_fuel_efficiency_asia = asia["fuel_efficiency_mpg"].max()

print("Q5 — Maximum fuel efficiency for cars from Asia:",
      max_fuel_efficiency_asia)

Q5 — Maximum fuel efficiency for cars from Asia: 41.2


Cell 9 — Q6: Median horsepower

In [11]:
# Step 1: Median before filling missing values
median_before = df["horsepower"].median()

# Step 2: Most frequent horsepower value
most_frequent_horsepower = df["horsepower"].mode()[0]

# Step 3: Fill missing horsepower values
df_filled = df.copy()

df_filled["horsepower"] = df_filled["horsepower"].fillna(
    most_frequent_horsepower
)

# Step 4: Median after filling missing values
median_after = df_filled["horsepower"].median()

print("Q6 — Horsepower")
print("-----------------------------")
print("Median before:", median_before)
print("Most frequent value:", most_frequent_horsepower)
print("Median after:", median_after)

if median_after > median_before:
    result = "Yes, it increased"
elif median_after < median_before:
    result = "Yes, it decreased"
else:
    result = "No"

print("Answer:", result)

Q6 — Horsepower
-----------------------------
Median before: 254.0
Most frequent value: 252.0
Median after: 252.0
Answer: Yes, it decreased


Cell 10 — Q7: Linear algebra calculation

In [12]:
# 1. Select all cars from Asia
asia = df[df["origin"] == "Asia"]

# 2. Select vehicle_weight and model_year
X_df = asia[["vehicle_weight", "model_year"]]

# 3. Select the first 7 values
X_df = X_df.head(7)

# 4. Get the underlying NumPy array
X = X_df.values

print("X:")
print(X)

# 5. Compute X^T X
XTX = X.T @ X

print("\nX^T X:")
print(XTX)

# 6. Invert X^T X
XTX_inv = np.linalg.inv(XTX)

print("\nInverse of X^T X:")
print(XTX_inv)

# 7. Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# 8. Compute w
w = XTX_inv @ X.T @ y

print("\nw:")
print(w)

# 9. Sum all elements
answer_q7 = w.sum()

print("\nQ7 — Sum of elements of w:", answer_q7)
print("Rounded answer:", round(answer_q7, 3))

X:
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

X^T X:
[[131950500  60750580]
 [ 60750580  28041424]]

Inverse of X^T X:
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

w:
[0.13644777 0.2327492 ]

Q7 — Sum of elements of w: 0.36919696904925486
Rounded answer: 0.369


Cell 11 — Final answers

In [13]:
print("=" * 50)
print("ML ZOOMCAMP 2026 — HOMEWORK 1")
print("FINAL ANSWERS")
print("=" * 50)

print(f"Q1 — Pandas version: {pd.__version__}")
print("Q2 — Records count: 10000")
print("Q3 — Fuel types: 3")
print("Q4 — Columns with missing values: 2")
print("Q5 — Max fuel efficiency for Asia: 41.2")
print("Q6 — Median horsepower changed: Yes, it decreased")
print("Q7 — Sum of weights: 0.369")

print("=" * 50)

ML ZOOMCAMP 2026 — HOMEWORK 1
FINAL ANSWERS
Q1 — Pandas version: 2.2.3
Q2 — Records count: 10000
Q3 — Fuel types: 3
Q4 — Columns with missing values: 2
Q5 — Max fuel efficiency for Asia: 41.2
Q6 — Median horsepower changed: Yes, it decreased
Q7 — Sum of weights: 0.369
